/**
 * @verifies docs/BACKLOG.md#SPK-17 · docs/DAT.md §23
 *
 * Le contrat est un fichier committe : ces tests le lisent, sans qu'aucun
 * sparkd ne tourne. C'est precisement ce que le §23.1 exige.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

import { OPENAPI_PATH, loadSchema, paths, methods } from './index.js';

test('le contrat est present dans le depot', () => {
  assert.ok(existsSync(OPENAPI_PATH), 'le contrat doit etre committe');
});

test('la console lit le contrat sans qu un sparkd tourne', () => {
  const schema = loadSchema();
  assert.equal(schema.openapi, '3.1.0');
  assert.ok(Object.keys(schema.paths).length >= 20);
});

test('les chemins attendus par la console sont declares', () => {
  const declares = paths();
  for (const chemin of [
    '/healthz', '/readyz', '/v1/host', '/v1/host/cores', '/v1/sparks',
    '/v1/ingress', '/v1/ssh-keys', '/v1/audit',
  ]) {
    assert.ok(declares.includes(chemin), `${chemin} doit etre declare`);
  }
});

test('les methodes d un chemin sont connues', () => {
  assert.deepEqual(methods('/v1/sparks'), ['GET', 'POST']);
  assert.deepEqual(methods('/v1/ssh-keys'), ['GET', 'POST']);
});

test('un chemin inexistant rend null, pas une erreur muette', () => {
  // Une route mal orthographiee doit se voir a l'ecriture, pas en production.
  assert.equal(methods('/v1/inexistant'), null);
});

test('les types TypeScript sont derives, pas ecrits a la main', () => {
  const types = readFileSync(new URL('./types.d.ts', import.meta.url), 'utf8');
  assert.match(types, /auto-generated by openapi-typescript/);
  assert.match(types, /Do not make direct changes/);
});
